version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "8000:8000"
    volumes:
      - ./surrealdb_data:/data
    command: start --log=info --user=root --pass=root -b 0.0.0.0:8000 surrealkv://data//database.db
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network
    restart: unless-stopped

  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-app
    depends_on:
      - surrealdb    
    environment:
      - SURREAL_BIND=ws://surrealdb:8000/
# these are currently not used
      - DATABASE_USER=root
      - DATABASE_PASS=root
      - DATABASE_NS=testns
      - DATABASE_DB=testdb
    networks:
      - app-network
    restart: on-failure:5

networks:
  app-network:
    driver: bridge
