version: '3.8'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    container_name: surrealdb
    ports:
      - "8000:8000"
    volumes:
      - ./surrealdb_data:/data
    command: start --log=info --user=root --pass=root -b 127.0.0.1:8000 surrealkv:/data/database.db
    networks:
      - app-network
    restart: unless-stopped

  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-app
    depends_on:
      - surrealdb    
    healthcheck:
      test: CMD curl -I http://surrealdb:8000/health
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    environment:
      - SURREAL_BIND=ws://surrealdb:8000/
# these are currently not used
      - DATABASE_USER=root
      - DATABASE_PASS=root
      - DATABASE_NS=testns
      - DATABASE_DB=testdb
    networks:
      - app-network
    restart: on-failure:1

networks:
  app-network:
    driver: bridge
